# Generated by Django 2.2.4 on 2019-12-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acc_is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
