# Generated by Django 2.2.4 on 2019-09-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('V', 'Void'), ('P', 'Pending'), ('S', 'Fully Paid'), ('F', 'Partially Paid')], default='P', max_length=1),
        ),
    ]
