# Generated by Django 2.2.4 on 2019-10-06 08:03

from decimal import Decimal
from django.db import migrations
import django.db.models.deletion
import djmoney.models.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_auto_20190918_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Bill', 'verbose_name_plural': 'Bill'},
        ),
        migrations.AlterField(
            model_name='billsetting',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='community', chained_model_field='community', on_delete=django.db.models.deletion.CASCADE, to='residents.Area'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='community', chained_model_field='community', on_delete=django.db.models.deletion.CASCADE, to='residents.Area'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='remainder',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='MYR', max_digits=14, verbose_name='Outstanding Amount'),
        ),
    ]
