# Generated by Django 2.2.4 on 2019-10-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0003_auto_20191006_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(upload_to='bankSlip/', verbose_name='Bank Slip'),
        ),
    ]
