# Generated by Django 2.2.4 on 2019-10-13 14:15

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_auto_20191012_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MYR', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(1)]),
        ),
    ]
