# Generated by Django 2.2.4 on 2019-10-13 15:37

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0005_auto_20191013_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='MYR', max_digits=14),
        ),
    ]
