# Generated by Django 2.2.4 on 2019-10-31 06:55

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0007_auto_20191022_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsetting',
            name='lots',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='area', chained_model_field='street__area', to='residents.Lot'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lot',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='area', chained_model_field='street__area', on_delete=django.db.models.deletion.CASCADE, to='residents.Lot'),
        ),
    ]
