# Generated by Django 2.2.4 on 2019-12-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('A', 'Announcement'), ('V', 'Visitor'), ('B', 'Billing'), ('F', 'Family')], max_length=1),
        ),
    ]
