# Generated by Django 2.2.4 on 2019-08-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billings.invoice',),
        ),
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billings.payment',),
        ),
        migrations.CreateModel(
            name='VisitReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('billings.payment',),
        ),
    ]
