# Generated by Django 2.2.4 on 2019-09-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentlotthroughmodel',
            options={'ordering': ('order',), 'verbose_name': 'Resident', 'verbose_name_plural': 'Residents'},
        ),
        migrations.AddField(
            model_name='lot',
            name='is_lock',
            field=models.BooleanField(default=False, verbose_name='Lock Property'),
        ),
    ]
