# Generated by Django 2.2.4 on 2019-09-18 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_auto_20190918_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='default_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_lot', to='residents.Lot'),
        ),
    ]
