# Generated by Django 2.2.4 on 2019-09-29 22:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_auto_20190929_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': "Resident's Request", 'verbose_name_plural': "Resident's Requests"},
        ),
        migrations.CreateModel(
            name='RequestFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approve'), ('R', 'Reject')], default='P', max_length=1)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Area')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Community')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Lot', verbose_name='House No.')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Street')),
            ],
            options={
                'verbose_name': "Resident's Family Request",
                'verbose_name_plural': "Resident's Family Requests",
            },
        ),
    ]
