# Generated by Django 2.2.4 on 2019-10-06 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_auto_20191005_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='name',
            field=models.CharField(max_length=150, verbose_name='House No.'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Street', verbose_name='Street No.'),
        ),
        migrations.AlterField(
            model_name='request',
            name='confirm',
            field=models.BooleanField(verbose_name='I confirm that the information given in this form is true, complete and accurate.'),
        ),
        migrations.AlterField(
            model_name='request',
            name='tou',
            field=models.BooleanField(verbose_name="I have read and agree to the <a href='#'>Privacy Policy</a>"),
        ),
        migrations.AlterField(
            model_name='resident',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Resident's Name"),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Street No.'),
        ),
    ]
