# Generated by Django 2.2.4 on 2019-10-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0007_auto_20191006_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfamily',
            name='requestor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
            preserve_default=False,
        ),
    ]
