# Generated by Django 2.2.4 on 2019-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0008_requestfamily_requestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentlotthroughmodel',
            name='disable_notification',
            field=models.BooleanField(default=False, verbose_name='Disable Notification'),
        ),
    ]
