# Generated by Django 2.2.4 on 2019-10-12 13:45

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0009_residentlotthroughmodel_disable_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='community', chained_model_field='community', on_delete=django.db.models.deletion.CASCADE, to='residents.Area'),
        ),
        migrations.AlterField(
            model_name='request',
            name='lot',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='street', chained_model_field='street', on_delete=django.db.models.deletion.CASCADE, to='residents.Lot'),
        ),
        migrations.AlterField(
            model_name='request',
            name='street',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='area', chained_model_field='area', on_delete=django.db.models.deletion.CASCADE, to='residents.Street'),
        ),
    ]
