# Generated by Django 2.2.4 on 2019-11-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0011_auto_20191031_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='tou',
            field=models.BooleanField(verbose_name="I have read and agree to the <a href='/static/ivms/file/PDPA.pdf'>Privacy Policy</a>"),
        ),
    ]
