# Generated by Django 2.2.4 on 2019-12-02 04:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0012_auto_20191127_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='I confirm that the information given in this form is true, complete and accurate.'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0178095303', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='tou',
            field=models.BooleanField(default=False, verbose_name="I have read and agree to the <a href='/static/ivms/file/PDPA.pdf'>Privacy Policy</a>"),
        ),
    ]
