# Generated by Django 2.2.4 on 2019-10-05 08:58

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='community', chained_model_field='community', on_delete=django.db.models.deletion.CASCADE, to='residents.Area'),
        ),
    ]
