# Generated by Django 2.2.4 on 2019-10-06 08:03

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20191005_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='community', chained_model_field='community', on_delete=django.db.models.deletion.CASCADE, to='residents.Area'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='publish_datetime',
            field=models.DateTimeField(verbose_name='Publish Date/Time'),
        ),
    ]
