# Generated by Django 2.2.7 on 2019-11-10 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20191022_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='thumbnail',
            field=models.ImageField(upload_to='announcement/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='Not more than 50 characters.', max_length=50),
        ),
    ]
