# Generated by Django 2.2.4 on 2019-12-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_auto_20191122_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='send_out',
            field=models.BooleanField(default=False),
        ),
    ]
