# Generated by Django 2.2.4 on 2019-08-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('EF', 'Entry Front Camera'), ('EB', 'Entry Back Camera'), ('IC', 'IC Camera'), ('XF', 'Exit Front Camera'), ('XB', 'Exit Back Camera'), ('FC', 'Face Camera')], default='EF', max_length=2)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Area')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Community')),
            ],
            options={
                'verbose_name_plural': 'IP Camera Settings',
            },
        ),
        migrations.CreateModel(
            name='Boomgate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('E', 'Entry Boomgate'), ('X', 'Exit Boomgate')], default='E', max_length=2)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Area')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Community')),
            ],
            options={
                'verbose_name_plural': 'Boomgate Settings',
            },
        ),
    ]
