# Generated by Django 2.2.4 on 2019-10-06 08:03

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ivms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boomgate',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='community', chained_model_field='community', on_delete=django.db.models.deletion.CASCADE, to='residents.Area'),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='community', chained_model_field='community', on_delete=django.db.models.deletion.CASCADE, to='residents.Area'),
        ),
    ]
