# Generated by Django 2.2.4 on 2019-08-24 10:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_notify', models.BooleanField(default=True)),
                ('qr_uuid', models.CharField(max_length=150)),
                ('entry_type', models.CharField(choices=[('E', 'Single Entry'), ('M', 'Multiple Entry'), ('S', 'Scheduled Entry')], max_length=1)),
                ('days', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=150)),
                ('visitor_car_plate', models.CharField(max_length=15)),
                ('visitor_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident')),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('car_plate', models.CharField(max_length=15)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Resident')),
            ],
        ),
        migrations.CreateModel(
            name='Track_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_image', models.ImageField(help_text='Driver Image', upload_to='driver/')),
                ('entry_car_plate_image', models.ImageField(help_text='Enter Carpate Image.', upload_to='entry/')),
                ('identity_image', models.ImageField(help_text='Exit Carpate Image.', upload_to='identity/')),
                ('exit_car_plate_image', models.ImageField(help_text='Exit Carpate Image.', upload_to='exit/')),
                ('status', models.CharField(choices=[('PEN', 'Pending entry'), ('AIR', 'Approved entry by resident'), ('RIR', 'Rejected entry by resident'), ('AIS', 'Approved entry by security guard'), ('RIS', 'Rejected entry by security guard'), ('PEX', 'Pending exit'), ('AOS', 'Approved exit by security guard'), ('ROS', 'Rejected exit by security guard')], max_length=3)),
                ('entry_type', models.CharField(choices=[('E', 'Single Entry'), ('M', 'Multiple Entry'), ('S', 'Scheduled Entry'), ('W', 'Walk In'), ('I', 'Impromptu')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_name', models.CharField(max_length=150)),
                ('visitor_car_plate', models.CharField(max_length=15)),
                ('visitor_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Area')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Community')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitors.Entry_Schedule')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Lot')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.Street')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitors.Visitors')),
            ],
        ),
        migrations.AddField(
            model_name='entry_schedule',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitors.Visitors'),
        ),
    ]
