# Generated by Django 2.2.4 on 2019-08-24 11:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_entry',
            name='exit_car_plate_image',
            field=models.ImageField(blank=True, help_text='Exit Carpate Image.', null=True, upload_to='exit/'),
        ),
        migrations.AlterField(
            model_name='track_entry',
            name='visitor_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
