# Generated by Django 2.2.4 on 2019-08-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20190824_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_entry',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Area'),
        ),
        migrations.AlterField(
            model_name='track_entry',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Community'),
        ),
    ]
