# Generated by Django 2.2.4 on 2019-08-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
        ('visitors', '0003_auto_20190824_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_entry',
            name='resident',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
            preserve_default=False,
        ),
    ]
