# Generated by Django 2.2.4 on 2019-08-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security_guards', '0001_initial'),
        ('visitors', '0004_track_entry_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_entry',
            name='passNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security_guards.PassNumber'),
        ),
        migrations.AlterField(
            model_name='track_entry',
            name='visitor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
