# Generated by Django 2.2.4 on 2019-09-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_auto_20190824_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track_entry',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Resident'),
        ),
    ]
