# Generated by Django 2.2.4 on 2019-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_auto_20190903_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_schedule',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry_schedule',
            name='qr_uuid',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entry_schedule',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry_schedule',
            name='visitor_name',
            field=models.CharField(max_length=1500),
        ),
    ]
