# Generated by Django 2.2.4 on 2019-09-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
        ('visitors', '0008_auto_20190907_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_schedule',
            name='lot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='residents.Lot'),
            preserve_default=False,
        ),
    ]
