# Generated by Django 2.2.4 on 2019-09-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0010_auto_20190907_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_entry',
            name='reason',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='track_entry',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Lot'),
        ),
        migrations.AlterField(
            model_name='track_entry',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residents.Street'),
        ),
    ]
