# Generated by Django 2.2.4 on 2019-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0012_track_entry_devicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
