# Generated by Django 2.2.4 on 2019-10-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0014_entry_schedule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_entry',
            name='with_vehicle',
            field=models.BooleanField(default=False),
        ),
    ]
