# Generated by Django 2.2.4 on 2019-12-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0017_auto_20191202_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='track_entry',
            name='send_out',
            field=models.BooleanField(default=False),
        ),
    ]
