# Generated by Django 2.2.4 on 2019-09-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_guards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='identity_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IC/Passport No.'),
        ),
    ]
