# Generated by Django 2.2.4 on 2019-12-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_guards', '0004_post_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_log',
            name='qr_uuid',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
